//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landlorder2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public int ID { get; set; }
        public System.DateTime ClockIn { get; set; }
        public System.DateTime ClockOut { get; set; }
        public Nullable<int> TimeWorked { get; set; }
        public string Employee { get; set; }
    }
}
